fix: Add exit status when status_code of curl to endpoint inside docker is not 200
Add exit status when status_code of curl to endpoint inside docker is not 200

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -121,6 +121,11 @@ jobs:
           if ! http_status=$(curl -s -XPOST -H 'Content-Type: application/json' -d '{"data":"This is a sample input text"}' http://localhost:5000/label); then
             echo "Warning: curl failed with $http_status!"
             exit 1
+          else
+            if http_status=$(curl -s -XPOST -H 'Content-Type: application/json' -d '{"data":"This is a sample input text"}' http://localhost:5000/label)  && [[ $http_status != "200" ]]; then
+              echo "Warning: curl failed with $http_status!"
+              exit 1
+            fi
           fi
 
        
